name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Build on linux systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cmake gcc-10 g++-10 libglu1-mesa-dev xorg-dev zenity zlib1g-dev
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: CMake
        run: cmake .
        shell: bash
        env:
          CC: gcc-10
          CXX: g++-10
      - name: Build
        run: make -j

  build_macos:
    name: Build on macOS
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: CMake
        run: cmake .
      - name: Build
        run: make -j

  build_windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Fetch newer Windows SDK
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 19041

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: CMake
        run: cmake -DCMAKE_SYSTEM_VERSION=10.0.19041.0 .
      - name: Build
        run: msbuild /v:m /p:Configuration=Release tev.sln
